stages:
  - lint
  - test
  - build
  - deploy

before_script:
  - ruby -v
  - which ruby
  - gem update --system
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rubocop:
  stage: lint
  script:
    - bundle exec rake rubocop

rspec:
  stage: test
  script:
    - bundle exec rake spec

build:
  stage: build
  script:
    - bundle exec rake build
  artifacts:
    untracked: true

deploy:
  stage: deploy
  environment:
    name: production
    url: http://rubygems.athenahealth.com
  script:
    - bundle exec gem inabox -g http://rubygems.athenahealth.com
  dependencies:
    - build
  only:
    - master@ladon/ladon
  when: manual
