AllCops:
  TargetRubyVersion: 2.1

# Antiquated line length settings overridden
Metrics/LineLength:
  Max: 120

# I'd rather someone be redundant but able to comprehend their code
# than use implicit returns and be confused about Ruby behavior.
Style/RedundantReturn:
  Enabled: false

# See comment above for Style/RedundantReturn
Style/RedundantBegin:
  Enabled: false

# See comment above for Style/RedundantReturn
Style/RedundantSelf:
  Enabled: false

# Bump up the limit
Metrics/MethodLength:
  CountComments: false
  Max: 20